- name: Make directories (/exports/*)
  file:
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items: "{{ lookup('file', 'volumes').split('\n') }}"
  become: yes

- name: Insert/Update configuration using a local file and validate it
  blockinfile:
    block: "{{ lookup('file', 'fstab') }}"
    dest: /etc/fstab
  become: yes