---
# tasks file for ansible-role-nis
#

- name: Template in a patched ypinit script that has the ctrl d prompt disabled that creates /var/yp/.csc
  template:
    src: ypinit_csc.j2
    dest: /usr/lib64/yp/ypinit_csc
    mode: 0755
    owner: root
    group: root
    backup: no
  when: nis_initialize|bool and nis_server|bool

- name: Template in the Makefile
  template:
    dest: /var/yp/Makefile
    src: Makefile.j2
    backup: yes
  when: nis_server|bool and nis_initialize|bool
  notify:
    - restart ypserv

- name: Initialize the master nis server with ypinit_csc if /var/yp/.csc does not exist
  command: /usr/lib64/yp/ypinit_csc -m creates=/var/yp/.csc
  when: nis_server|bool and nis_initialize|bool and ansible_virtualization_type != "docker"

