---
# handlers file for ansible-role-nis

- name: restart rpcbind
  service: name=rpcbind state=restarted

- name: restart ypbind
  service: name=ypbind state=restarted
  when: not nis_server|bool

- name: restart ypserv
  service: name=ypserv state=restarted
  when: nis_server|bool

# TODO: This creates a bunch of files in /var/yp/ not in /var/yp/domainname/..
#- name: ypmake
#  command: make all chdir=/var/yp
#  when: nis_server
