---
# Ansible role defaults to install cobbler - main.yml
#
# Copyright (C) 2016  JingchengYang <yjcyxky@163.com>
#

cobbler_packages:
    - cobbler
    - cobbler-web
    - dnsmasq
    - syslinux
    - pykickstart
    - xinetd
    - dhcp

cobbler_services:
    - httpd
    - cobblerd
    - xinetd

dns_module: manage_dnsmasq
dhcp_module: manage_isc

...
